"""Tribunal registry: config-driven definitions for each supported tribunal."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Optional


@dataclass(frozen=True)
class TribunalConfig:
    tribunal_id: str
    display_name: str
    source_mode: str  # batch_from_raw_pdfs | scrape_pdf | import_json
    storage_account_raw: str
    container_raw: str
    raw_prefix: str
    storage_account_parsed: str
    container_parsed: str
    parsed_prefix: str
    parser_id: str
    text_strategy: str  # head | full_text
    authority_score: float
    uf: Optional[str]
    enabled: bool


TRIBUNAL_CONFIGS: Dict[str, TribunalConfig] = {
    "tce-sp": TribunalConfig(
        tribunal_id="tce-sp",
        display_name="TCE-SP",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-sp/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-sp/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="SP",
        enabled=True,
    ),
    "tcu": TribunalConfig(
        tribunal_id="tcu",
        display_name="TCU",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tcu/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tcu/",
        parser_id="tce_parser_v3",
        text_strategy="full_text",
        authority_score=0.90,
        uf=None,
        enabled=True,
    ),
    "tce-mg": TribunalConfig(
        tribunal_id="tce-mg",
        display_name="TCE-MG",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-mg/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-mg/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="MG",
        enabled=True,
    ),
    "tce-sc": TribunalConfig(
        tribunal_id="tce-sc",
        display_name="TCE-SC",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-sc/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-sc/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="SC",
        enabled=True,
    ),
    "tce-pr": TribunalConfig(
        tribunal_id="tce-pr",
        display_name="TCE-PR",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-pr/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-pr/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="PR",
        enabled=True,
    ),
    "tce-es": TribunalConfig(
        tribunal_id="tce-es",
        display_name="TCE-ES",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-es/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-es/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="ES",
        enabled=True,
    ),
    "tce-pa": TribunalConfig(
        tribunal_id="tce-pa",
        display_name="TCE-PA",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-pa/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-pa/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="PA",
        enabled=True,
    ),
    "tce-ce": TribunalConfig(
        tribunal_id="tce-ce",
        display_name="TCE-CE",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-ce/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-ce/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="CE",
        enabled=True,
    ),
    "tce-pb": TribunalConfig(
        tribunal_id="tce-pb",
        display_name="TCE-PB",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-pb/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-pb/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="PB",
        enabled=True,
    ),
    "tce-am": TribunalConfig(
        tribunal_id="tce-am",
        display_name="TCE-AM",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-am/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-am/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="AM",
        enabled=True,
    ),
    "tce-rj": TribunalConfig(
        tribunal_id="tce-rj",
        display_name="TCE-RJ",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-rj/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tce-rj/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="RJ",
        enabled=True,
    ),
    "tce-rn": TribunalConfig(
        tribunal_id="tce-rn",
        display_name="TCE-RN",
        source_mode="import_json",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-rn/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="tce-rn/",
        parser_id="tce_rn_json",
        text_strategy="full_text",
        authority_score=0.80,
        uf="RN",
        enabled=True,
    ),
    "tce-mt": TribunalConfig(
        tribunal_id="tce-mt",
        display_name="TCE-MT",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-mt/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="tce-mt/",
        parser_id="tce_mt_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.80,
        uf="MT",
        enabled=True,
    ),
    "tce-ba": TribunalConfig(
        tribunal_id="tce-ba",
        display_name="TCE-BA",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-ba/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="tce-ba/",
        parser_id="tce_parser_v3",
        text_strategy="full_text",
        authority_score=0.80,
        uf="BA",
        enabled=True,
    ),
    "tce-go": TribunalConfig(
        tribunal_id="tce-go",
        display_name="TCE-GO",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-go/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="tce-go/",
        parser_id="tce_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.80,
        uf="GO",
        enabled=True,
    ),
    "trf3": TribunalConfig(
        tribunal_id="trf3",
        display_name="TRF3",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="trf3/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf3/",
        parser_id="trf3_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "trf1": TribunalConfig(
        tribunal_id="trf1",
        display_name="TRF1",
        source_mode="import_json",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="cjf/acordaos/cjf--TRF1--",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf1/",
        parser_id="trf1_cjf_metadata_v1",
        text_strategy="head",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "trf4": TribunalConfig(
        tribunal_id="trf4",
        display_name="TRF4",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="trf4/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf4/",
        parser_id="trf4_html_v1",
        text_strategy="full_text",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "trf6": TribunalConfig(
        tribunal_id="trf6",
        display_name="TRF6",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="trf6/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf6/",
        parser_id="trf6_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "trf2": TribunalConfig(
        tribunal_id="trf2",
        display_name="TRF2",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="trf2/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf2/",
        parser_id="trf2_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "trf5": TribunalConfig(
        tribunal_id="trf5",
        display_name="TRF5",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="trf5/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="trf5/",
        parser_id="trf5_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.85,
        uf=None,
        enabled=True,
    ),
    "tce-rs": TribunalConfig(
        tribunal_id="tce-rs",
        display_name="TCE-RS",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tce-rs/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="tce-rs/",
        parser_id="tce_parser_v3",
        text_strategy="full_text",
        authority_score=0.80,
        uf="RS",
        enabled=True,
    ),
    "tcm-sp": TribunalConfig(
        tribunal_id="tcm-sp",
        display_name="TCM-SP",
        source_mode="batch_from_raw_pdfs",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="tcm-sp/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="juris-parsed",
        parsed_prefix="tcm-sp/",
        parser_id="tce_parser_v3",
        text_strategy="head",
        authority_score=0.80,
        uf="SP",
        enabled=True,
    ),
    "stj-acor": TribunalConfig(
        tribunal_id="stj-acor",
        display_name="STJ-ACOR",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="stj/acor/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="stj/",
        parser_id="stj_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.90,
        uf=None,
        enabled=True,
    ),
    "stj-baen": TribunalConfig(
        tribunal_id="stj-baen",
        display_name="STJ-BAEN",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="stj/baen/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="stj/",
        parser_id="stj_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.90,
        uf=None,
        enabled=True,
    ),
    "stf": TribunalConfig(
        tribunal_id="stf",
        display_name="STF",
        source_mode="batch_from_raw_jsons",
        storage_account_raw="sttcejurisprudencia",
        container_raw="juris-raw",
        raw_prefix="stf/acordaos/",
        storage_account_parsed="stgovyparsetestsponsor",
        container_parsed="kb-raw",
        parsed_prefix="stf/",
        parser_id="stf_json_inline_v1",
        text_strategy="full_text",
        authority_score=0.95,
        uf=None,
        enabled=True,
    ),
}


def get_config(tribunal_id: str) -> TribunalConfig:
    cfg = TRIBUNAL_CONFIGS.get(tribunal_id)
    if cfg is None:
        raise ValueError(f"Tribunal desconhecido: {tribunal_id}. Validos: {list(TRIBUNAL_CONFIGS.keys())}")
    return cfg
